development: &defaults
  client_id: 1055906996108-9j83chu1l3dspp3rk37dr4sjdge6eh8h.apps.googleusercontent.com
  client_secret: yPyY-lvwJPd6WVnpeLu315mu
  issuer: http://accounts.google.com
  redirect_uri: http://op.dev/connect/google

test:
  <<: *defaults

production:
  <<: *defaults
  redirect_uri: https://intense-retreat-62302.herokuapp.com/connect/google
